In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

TASK - 1

In [ ]:
tf.strings.join(['18383745','Johnson','Johnson@mail.com','4568797','Mumbai','Male','09/10/1975'], separator="~")

<tf.Tensor: shape=(), dtype=string, numpy=b'18383745~Johnson~Johnson@mail.com~4568797~Mumbai~Male~09/10/1975'>

TASK - 2 

In [ ]:
matrix=[['indigo','violet','programmer','computer','training','kitchen','array','instagram','bluetooth']]
matrix=np.array(matrix)
print(matrix[0].reshape(3,3))

[['indigo' 'violet' 'programmer']
 ['computer' 'training' 'kitchen']
 ['array' 'instagram' 'bluetooth']]


TASK - 3

In [ ]:
product_price=tf.constant(1895.2)


In [ ]:
print(product_price)

tf.Tensor(1895.2, shape=(), dtype=float32)


In [ ]:
#data type float16
product_price=tf.constant(1895.2,tf.float16)


In [ ]:
print(product_price)

tf.Tensor(1895.0, shape=(), dtype=float16)


TASK - 4

In [ ]:
# marks = np.random.randint(16, size=(5, 3))
#marks=marks.astype(np.int16)
#print(marks)   
marks = np.round(np.random.uniform(100,200,15).reshape(-1,3),5)           

In [ ]:
marks=tf.constant(marks,tf.int16)

In [ ]:
print(marks)

tf.Tensor(
[[130 149 138]
 [169 165 114]
 [130 182 107]
 [123 131 153]
 [143 142 101]], shape=(5, 3), dtype=int16)


In [ ]:
marks1=tf.Variable(marks)
marks1.shape

TensorShape([5, 3])

In [ ]:
for x in range(len(marks)):
  for y in range(len(marks[x])):
    marks1[x,y].assign(np.random.randint(100, 200))
print(marks1)               

<tf.Variable 'Variable:0' shape=(5, 3) dtype=int16, numpy=
array([[135, 193, 182],
       [142, 169, 147],
       [184, 131, 150],
       [194, 114, 196],
       [100, 180, 121]], dtype=int16)>


TASK - 6 

In [ ]:
currency = {'India':'Rupee', 'America':'Dollar','Saudi Arabia':'Riyal'}

t_currency = tf.convert_to_tensor(list(currency.items()))
print(t_currency)  


tf.Tensor(
[[b'India' b'Rupee']
 [b'America' b'Dollar']
 [b'Saudi Arabia' b'Riyal']], shape=(3, 2), dtype=string)


In [ ]:
tensor1=tf.convert_to_tensor(list(currency.keys()))

In [ ]:
print(tensor1)

tf.Tensor([b'India' b'America' b'Saudi Arabia'], shape=(3,), dtype=string)


In [ ]:
tensor2=tf.convert_to_tensor(list(currency.values()))

In [ ]:
print(tensor2)

tf.Tensor([b'Rupee' b'Dollar' b'Riyal'], shape=(3,), dtype=string)


In [ ]:
# shape and size of the tensor
print("Shape of tensor1 :",tf.shape(tensor1))
print("Size of tensor1 :",tf.size(tensor1))

print("Shape of tensor2 :",tf.shape(tensor2))
print("Size of tensor2 :",tf.size(tensor2))



Shape of tensor1 : tf.Tensor([3], shape=(1,), dtype=int32)
Size of tensor1 : tf.Tensor(3, shape=(), dtype=int32)
Shape of tensor2 : tf.Tensor([3], shape=(1,), dtype=int32)
Size of tensor2 : tf.Tensor(3, shape=(), dtype=int32)


  TASK - 7

In [ ]:
unit=tf.constant(np.random.randint(1,10,4))
unit_price=tf.constant(np.random.randint(100,5000,4))


In [ ]:
price= (unit * unit_price)

In [ ]:
grand_total= sum(price)

In [ ]:
print("Grand total price of all the product/units :",grand_total)     

Grand total price of all the product/units : tf.Tensor(79500, shape=(), dtype=int64)
