In [8]:
import numpy as np
from numpy import genfromtxt

std_details= genfromtxt('DS1_C4_S2_Admission_Predict_Practice.csv', delimiter=',', skip_header=1)
print(std_details)


[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [12]:
# TASK- 1
import numpy as np
ind=np.where(std_details[:,1]>320)
print("Students with GRE score greater than 320:\n",std_details[ind])

Students with GRE score greater than 320:
 [[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  4.   322.   110.   ...   8.67   1.     0.8 ]
 ...
 [397.   325.   107.   ...   9.11   1.     0.84]
 [398.   330.   116.   ...   9.45   1.     0.91]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [13]:
# TASK- 2
ind=np.where(std_details[:,2]>110)
print("Students with TOEFL greater than 110 :\n",std_details[ind])

Students with TOEFL greater than 110 :
 [[  1.   337.   118.   ...   9.65   1.     0.92]
 [  6.   330.   115.   ...   9.34   1.     0.9 ]
 [ 12.   327.   111.   ...   9.     1.     0.84]
 ...
 [395.   329.   111.   ...   9.23   1.     0.89]
 [398.   330.   116.   ...   9.45   1.     0.91]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [20]:
# TASK- 3
import numpy as np
from numpy import genfromtxt

std_details= genfromtxt('DS1_C4_S2_Admission_Predict_Practice.csv', delimiter=',', skip_header=1)

sort_gre=np.sort(std_details[:,1])[::-1]
print(sort_gre[0:11])
ind_gre=np.where(std_details[:,1]>=339)
print("List of top 11 GRE students:\n",std_details[ind_gre])
sort_toefl=np.sort(std_details[:,2])[::-1]
ind_toefl=np.where(std_details[:,2]==120)
print("The list of top 8 TOEFL students:\n",std_details[ind_toefl])

[340. 340. 340. 340. 340. 340. 340. 340. 339. 339. 339.]
List of top 11 GRE students:
 [[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 34.   340.   114.     5.     4.     4.     9.6    1.     0.9 ]
 [ 48.   339.   119.     5.     4.5    4.     9.7    0.     0.89]
 [ 82.   340.   120.     4.     5.     5.     9.5    1.     0.96]
 [ 85.   340.   115.     5.     4.5    4.5    9.45   1.     0.94]
 [131.   339.   114.     5.     4.     4.5    9.76   1.     0.96]
 [144.   340.   120.     4.     4.5    4.     9.92   1.     0.97]
 [149.   339.   116.     4.     4.     3.5    9.8    1.     0.96]
 [203.   340.   120.     5.     4.5    4.5    9.91   1.     0.97]
 [285.   340.   112.     4.     5.     4.5    9.66   1.     0.94]
 [385.   340.   113.     4.     5.     5.     9.74   1.     0.96]]
The list of top 8 TOEFL students:
 [[ 26.   340.   120.     5.     4.5    4.5    9.6    1.     0.94]
 [ 82.   340.   120.     4.     5.     5.     9.5    1.     0.96]
 [ 98.   331.   120

In [18]:
#TASK - 4
ind=np.where(((std_details[:,1]>299)&(std_details[:,1]<306))&(std_details[:,4]==3.5)&(std_details[:,7]==1))
std_details1=std_details[ind]
print(std_details1)
print("The serial no and toefl scores of these students=",std_details1[:,[0,2]])

[[1.130e+02 3.010e+02 1.070e+02 3.000e+00 3.500e+00 3.500e+00 8.340e+00
  1.000e+00 6.200e-01 9.581e+03]
 [2.100e+02 3.010e+02 1.040e+02 3.000e+00 3.500e+00 4.000e+00 8.120e+00
  1.000e+00 6.800e-01 9.516e+03]
 [3.580e+02 3.010e+02 1.040e+02 2.000e+00 3.500e+00 3.500e+00 7.890e+00
  1.000e+00 6.800e-01 9.085e+03]]
The serial no and toefl scores of these students= [[113. 107.]
 [210. 104.]
 [358. 104.]]


In [29]:
# TASK- 5 
import numpy as np
from numpy import genfromtxt

std_details= genfromtxt('DS1_C4_S2_Admission_Predict_Practice.csv', delimiter=',', skip_header=1)
scholarship=np.random.randint(5000,10000,size=(400,1))
std_details=np.append(std_details,scholarship,axis=1)
scholarship = std_details[:,9]
print("Scholorships :\n",scholarship)
index = np.where(std_details[:,9] > 9000) 
print("Number of student with scholarship greater than 9000 are: ",np.count_nonzero(index))

Scholorships :
 [8609. 9980. 7983. 5818. 5426. 8344. 8904. 9500. 7401. 8777. 7909. 7159.
 5112. 6595. 8602. 5094. 6333. 7087. 9795. 9551. 5402. 8843. 6507. 6175.
 6553. 9862. 9155. 6760. 5254. 7678. 5813. 7685. 9368. 5037. 6635. 6891.
 5231. 8778. 9686. 8138. 8151. 7916. 7934. 5058. 8407. 7284. 6140. 5477.
 9453. 5831. 6497. 5823. 6416. 5829. 7783. 5476. 7119. 8855. 9415. 8056.
 9945. 6516. 7110. 8283. 5363. 7337. 7291. 6484. 7183. 8892. 9761. 9831.
 5989. 5743. 6693. 7441. 8537. 7694. 8417. 8354. 5812. 8742. 6874. 5197.
 6944. 7780. 6486. 5624. 8339. 6234. 8715. 9001. 5261. 5288. 8082. 6463.
 7189. 9809. 9424. 5390. 9068. 5083. 7392. 5220. 9527. 7753. 8727. 5021.
 9898. 5620. 5089. 9413. 7296. 5275. 6806. 5076. 6997. 7222. 7633. 6635.
 5426. 5741. 7231. 6562. 6676. 9921. 9892. 8004. 9163. 8738. 5439. 9479.
 6826. 5343. 6649. 8025. 6907. 8281. 5118. 9263. 6926. 9745. 8833. 9047.
 5434. 6781. 5099. 8228. 9932. 9566. 5154. 8182. 6047. 7496. 8064. 9859.
 7365. 6911. 6305. 5032. 8396. 5848

In [92]:
# TASK-6
import numpy as np
#ind=np.where(scholarship>9000)
#abc=ind
a=std_details[:,4],np.where(scholarship>9000) 
b=std_details[:,5],np.where(scholarship>9000)


print("SOP scores/ id of the students who's scholarship is greater than 9000:\n",a)
print("LOR scores/ id of the students who's scholarship is greater than 9000:\n",b)



SOP scores/ id of the students who's scholarship is greater than 9000:
 (array([4.5, 4. , 3. , 3.5, 2. , 4.5, 3. , 3. , 2. , 3.5, 3.5, 4. , 4. ,
       4. , 3.5, 3.5, 4. , 4. , 4. , 3.5, 3. , 3. , 5. , 5. , 4. , 4.5,
       4.5, 1.5, 2. , 1.5, 3. , 4. , 3. , 4. , 4. , 5. , 4. , 1. , 3. ,
       4. , 3.5, 2.5, 2.5, 4.5, 4.5, 5. , 4. , 4.5, 3.5, 3. , 2.5, 1.5,
       4. , 4. , 3. , 3. , 2. , 4. , 3. , 2. , 3. , 4. , 3. , 4. , 3. ,
       3.5, 3. , 3.5, 3.5, 4.5, 5. , 5. , 5. , 4.5, 3. , 2. , 3. , 3. ,
       3. , 1.5, 2. , 5. , 5. , 4. , 4.5, 4.5, 4.5, 3.5, 4.5, 4.5, 4. ,
       5. , 4. , 3. , 2. , 1.5, 3. , 4. , 5. , 4. , 3.5, 2.5, 4. , 4.5,
       3.5, 4. , 4.5, 3.5, 5. , 5. , 3. , 4. , 3.5, 4. , 3.5, 4.5, 4. ,
       2. , 3. , 3. , 5. , 4.5, 1.5, 3.5, 2.5, 2. , 4. , 2.5, 3.5, 5. ,
       4. , 5. , 3.5, 4. , 4. , 3.5, 5. , 1.5, 4.5, 3.5, 4. , 4.5, 4. ,
       4.5, 3. , 2. , 2. , 3. , 4. , 3.5, 4. , 5. , 5. , 3. , 3. , 3. ,
       2. , 2. , 2. , 1.5, 1.5, 1.5, 3. , 3.5, 4.5, 4.5, 3.5, 2

In [84]:
# TASK-7
import numpy as np
gresc=np.where((std_details[:,1]>315) | (std_details[:,2]>115))
new_sch=scholarship+1000
#gresc=scholarship+1000     
print("Serial number of students who are eligible for $1000 scholarship:\n",gresc)
print("Total Number of students who are eligible for $1000 scholarship: ",np.count_nonzero(gresc))
print("Updated scholarship:\n",new_sch)


Serial number of students who are eligible for $1000 scholarship:
 (array([  0,   1,   2,   3,   5,   6,   9,  10,  11,  12,  16,  17,  18,
        21,  22,  23,  24,  25,  26,  31,  32,  33,  34,  35,  41,  43,
        44,  45,  46,  47,  48,  49,  52,  53,  54,  55,  56,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  75,  76,  81,  82,  83,  84,
        85,  87,  89,  90,  97,  98,  99, 100, 103, 104, 105, 106, 107,
       108, 111, 113, 119, 120, 121, 126, 127, 128, 129, 130, 133, 134,
       137, 138, 139, 140, 141, 142, 143, 144, 145, 147, 148, 150, 151,
       152, 153, 154, 162, 163, 164, 165, 171, 172, 173, 174, 175, 176,
       177, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 200,
       202, 203, 210, 211, 212, 213, 214, 215, 216, 217, 218, 221, 222,
       228, 229, 231, 234, 235, 236, 237, 241, 242, 243, 245, 246, 248,
       249, 250, 251, 252, 253, 254, 257, 258, 259, 260, 263, 264, 268,
       275, 276, 277, 281, 283, 284, 285, 286, 287, 294, 295, 297, 2

In [ ]:
# Additional Questions

In [57]:
# TASK- 8 
import numpy as np
cgs=np.where ((std_details[:,6]>=8.0) & (std_details[:,6]<=8.5))
print("Total number of students who's cgpa is between 8.0 to 8.5 : ",np.count_nonzero(cgs))

Total number of students who's cgpa is between 8.0 to 8.5 :  122


In [65]:
# TASK- 9
import numpy as np
avrg_sop=np.mean(std_details[:,4])
print("Average SOP : ",avrg_sop)
avrg_lor=np.mean(std_details[:,5])
print("Average LOR : ",avrg_lor)
if avrg_sop>avrg_lor:
    per=avrg_lor/avrg_sop*100
    print("SOP average is more than LOR average score by %:",per)
else:
    print("SOP average score is less than LOR average score:")


Average SOP :  3.4
Average LOR :  3.4525
SOP average score is less than LOR average score:


In [74]:
# TASK- 10
# Measure of spread 
import statistics


print("Variance of scholarship amount among all the students: ",statistics.variance(scholarship))
print("PVariance of scholarship amount among all the students: ",statistics.pvariance(scholarship))
print("Standard deviation of scholarship amount among all the students: ",statistics.stdev(scholarship))



Variance of scholarship amount among all the students:  2255819.6546303257
PVariance of scholarship amount among all the students:  2250180.10549375
Standard deviation of scholarship amount among all the students:  1501.9386321119534


In [78]:
print(scholarship+1000)

[10515. 10083.  7818.  8733.  7952.  9215.  8676. 10755.  6098.  8914.
  7649.  6772.  7511.  7356.  8069.  7608. 10223.  7441.  9618. 10248.
 10542.  9440.  6224.  7440.  6934.  9628. 10663. 10795.  6251.  6980.
 10149.  9341. 10574. 10164.  9458. 10581.  8255.  6016. 10061. 10010.
 10191.  7265.  6734. 10454.  6511.  9821.  9872. 10600.  9766.  9519.
  7796.  9922.  8535.  8011.  9517. 10581.  9830.  9361.  9704.  9928.
  7059.  9632.  6217.  9219.  8150.  6065. 10033.  9441.  9258.  7126.
  8353.  6358.  9723. 10177.  8004.  6924.  6474.  8009.  6917. 10329.
  9556.  9143.  6677. 10685. 10111.  8554.  8160.  8934.  8994.  7206.
  6493.  6922.  7004. 10531.  7939. 10827.  6004. 10634.  8466. 10063.
  9633.  9361.  7111.  9197.  8848.  7335.  9543.  7977.  7441. 10720.
  6969.  9680. 10395.  6435.  7471. 10849.  6930.  6276.  7574. 10500.
  9578.  6588.  7715.  9322. 10471.  8093. 10672.  6709.  6132.  6837.
  7087.  6054.  6865.  6334.  6304.  7100.  7158.  7458.  8557.  9849.
  7138