In [66]:
#TASK - 1

import numpy as np
hrempId = np.arange(1,501)
print("HR Department employees:\n",hrempId)

HR Department employees:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 

In [67]:
import numpy as np
fnempId = np.arange(501,1001)
print("FINANCE Department employees:\n",fnempId)

FINANCE Department employees:
 [ 501  502  503  504  505  506  507  508  509  510  511  512  513  514
  515  516  517  518  519  520  521  522  523  524  525  526  527  528
  529  530  531  532  533  534  535  536  537  538  539  540  541  542
  543  544  545  546  547  548  549  550  551  552  553  554  555  556
  557  558  559  560  561  562  563  564  565  566  567  568  569  570
  571  572  573  574  575  576  577  578  579  580  581  582  583  584
  585  586  587  588  589  590  591  592  593  594  595  596  597  598
  599  600  601  602  603  604  605  606  607  608  609  610  611  612
  613  614  615  616  617  618  619  620  621  622  623  624  625  626
  627  628  629  630  631  632  633  634  635  636  637  638  639  640
  641  642  643  644  645  646  647  648  649  650  651  652  653  654
  655  656  657  658  659  660  661  662  663  664  665  666  667  668
  669  670  671  672  673  674  675  676  677  678  679  680  681  682
  683  684  685  686  687  688  689  690  691 

In [68]:
import numpy as np
itempId = np.arange(1001,1501)
print("IT Department employees:\n",itempId)

IT Department employees:
 [1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112
 1113 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126
 1127 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140
 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154
 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168
 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182
 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 

In [69]:
import numpy as np
slempId = np.arange(1501,2001)
print("SALES Department employees:\n",slempId)

SALES Department employees:
 [1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 16

In [71]:
#TASK 2 

import numpy as np
HR_sal = np.random.randint(25000,50000,500)
print("HR Employees Salaries:\n",HR_sal)
Finance_sal=HR_sal*1.25
print("Finance Employees Salaries:\n",Finance_sal)
Sales_sal=Finance_sal*0.5
print("Sales Employees Salaries:\n",Sales_sal)
IT_sal=HR_sal+5000
print("IT Employee Salaries:\n",IT_sal)


HR Employees Salaries:
 [40509 32691 34569 38505 33725 34903 34846 37095 31310 49301 27291 35820
 39374 45318 41300 29782 29102 47097 44875 27452 26459 31299 45192 44105
 26379 47602 26021 49121 30480 42857 36900 25568 40065 41314 37083 35363
 44434 31882 36813 29160 28616 35341 36837 42607 31714 48587 47730 34210
 27495 28039 35523 36057 31275 35574 26887 34500 33275 42283 29549 28970
 43488 42015 33548 29200 42562 42148 31028 26269 32240 28319 38900 34490
 37810 35760 29304 48309 35740 35538 47655 31583 29115 28055 47333 28619
 41744 43801 47821 36083 47649 38928 45092 38565 26015 30005 27942 45095
 48114 49450 31369 45694 28608 30216 35366 28420 48334 32543 44126 38351
 42368 39120 31702 26376 31001 46603 34580 35683 48920 30674 48024 35947
 47064 32127 34234 34109 28264 28357 43384 42290 46335 48030 42433 38793
 29853 45707 40005 39691 39744 49161 38012 25200 28259 26764 42131 28887
 45643 35942 36767 44084 32127 48463 36450 37707 43836 40806 43440 32693
 46529 28977 48454 38114 43

In [72]:
#TASK - 3

import numpy as np
Tot_HR=np.sum(HR_sal)
Tot_Finance=np.sum(Finance_sal)
Tot_IT=sum(IT_sal)
Tot_Sales=sum(Sales_sal)
print("Total HR salaries: ",Tot_HR)
print("Total Finance salaries: ",Tot_Finance)
print("Total IT salaries: ",Tot_IT)
print("Total Sales salaries: ",Tot_Sales)


Total HR salaries:  18630159
Total Finance salaries:  23287698.75
Total IT salaries:  21130159
Total Sales salaries:  11643849.375


In [73]:
print("Finance depertment cost more to the company:")

Finance depertment cost more to the company:


In [80]:
#TASK - 4
sal_HR=np.sort(HR_sal)[-1:-11:-1]
print("Top 10 salary of HR Department:\n",sal_HR)
print("Sum of top 10 salary of HR Department: ",sal_HR.sum())

sal_Finance=np.sort(Finance_sal)[-1:-11:-1]
print("Top 10 salary of Finance Department:\n",sal_Finance)
print("Sum of top 10 salary of Finance Department: ",sal_Finance.sum())

sal_Sales=np.sort(Sales_sal)[-1:-11:-1]
print("Top 10 salary of Sales Department:\n",sal_Sales)
print("Sum of top 10 salary of Sales Department: ",sal_Sales.sum())

sal_IT=np.sort(IT_sal)[-1:-11:-1]
print("Top 10 salary of IT Department:\n",sal_IT)
print("Sum of top 10 salary of IT Department: ",sal_IT.sum())




Top 10 salary of HR Department:
 [49956 49888 49878 49801 49783 49770 49582 49450 49301 49161]
Sum of top 10 salary of HR Department:  496570
Top 10 salary of Finance Department:
 [62445.   62360.   62347.5  62251.25 62228.75 62212.5  61977.5  61812.5
 61626.25 61451.25]
Sum of top 10 salary of Finance Department:  620712.5
Top 10 salary of Sales Department:
 [31222.5   31180.    31173.75  31125.625 31114.375 31106.25  30988.75
 30906.25  30813.125 30725.625]
Sum of top 10 salary of Sales Department:  310356.25
Top 10 salary of IT Department:
 [54956 54888 54878 54801 54783 54770 54582 54450 54301 54161]
Sum of top 10 salary of IT Department:  546570


In [81]:
#TASK - 5

salhr=np.count_nonzero(HR_sal>45000)
salfin=np.count_nonzero(Finance_sal>45000)
salsal=np.count_nonzero(Sales_sal>45000)
salit=np.count_nonzero(IT_sal>45000)
totalemp= salhr+salfin+salsal+salit
print("Total number of employees with salary more than 45000 that are eligible for 10% increment: ",totalemp)


Total number of employees with salary more than 45000 that are eligible for 10% increment:  565


In [86]:
#TASK - 6

sales=np.where(Sales_sal<20000, Sales_sal*1.20, Sales_sal)
Sales_sal=sales.copy()
print("Sales employees:\n",Sales_sal)
print("Employees with 20% increment:\n", sales)


Sales employees:
 [25318.125 20431.875 21605.625 24065.625 21078.125 21814.375 21778.75
 23184.375 23482.5   30813.125 20468.25  22387.5   24608.75  28323.75
 25812.5   22336.5   21826.5   29435.625 28046.875 20589.    23813.1
 23474.25  28245.    27565.625 23741.1   29751.25  23418.9   30700.625
 22860.    26785.625 23062.5   23011.2   25040.625 25821.25  23176.875
 22101.875 27771.25  23911.5   23008.125 21870.    21462.    22088.125
 23023.125 26629.375 23785.5   30366.875 29831.25  21381.25  20621.25
 21029.25  22201.875 22535.625 23456.25  22233.75  20165.25  21562.5
 20796.875 26426.875 22161.75  21727.5   27180.    26259.375 20967.5
 21900.    26601.25  26342.5   23271.    23642.1   20150.    21239.25
 24312.5   21556.25  23631.25  22350.    21978.    30193.125 22337.5
 22211.25  29784.375 23687.25  21836.25  21041.25  29583.125 21464.25
 26090.    27375.625 29888.125 22551.875 29780.625 24330.    28182.5
 24103.125 23413.5   22503.75  20956.5   28184.375 30071.25  30906.25
 235

In [89]:
# TASK 7

newDup=slempId.copy()
#print(newDup)
newDup=np.delete(newDup, np.where(newDup>=1996))
#print(newDup)
new=np.arange(2001,2006)
newDup=np.append(newDup,new)
print(newDup)

[1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 

In [ ]:
# Additional Questions


In [97]:
# TASK- 8

total_hr=np.sum(HR_sal)
total_sales=np.sum(Sales_sal)

percen=(total_sales/total_hr)*100
print("Total salary of HR department is greater than Sales department by %f %%" %percen)
avrg_hr=np.mean(HR_sal)
print("Average salary of HR department is: ",avrg_hr)
avrg_sales=np.mean(Sales_sal)
print("Average salary of Sales department is: ",avrg_sales)


Total salary of HR department is greater than Sales department by 65.932825 %
Average salary of HR department is:  37260.318
Average salary of Sales department is:  24566.7801


In [119]:
# TASK- 9

sumofemp=np.where(np.logical_and(Finance_sal>=50000, Finance_sal<=55000))
res=np.count_nonzero(sumofemp)
print("Number of employees from Finance Department salary between 50000-55000 are: ",res)


Number of employees from Finance Department salary between 50000-55000 are:  77
(array([  0,  14,  29,  32,  33,  43,  57,  60,  61,  64,  65,  84,  85,
       108, 126, 127, 130, 134, 142, 152, 153, 154, 160, 161, 180, 210,
       213, 218, 229, 240, 245, 248, 256, 260, 261, 273, 277, 286, 287,
       293, 295, 301, 308, 314, 315, 334, 348, 355, 362, 366, 372, 379,
       381, 382, 393, 401, 414, 421, 428, 431, 434, 436, 442, 447, 450,
       453, 459, 464, 471, 472, 474, 475, 476, 477, 478, 486, 494, 499],
      dtype=int64),)


In [112]:
pwd


'C:\\Users\\Manish'

In [117]:
# TASK 10

from numpy import genfromtxt

emp_details= genfromtxt('DS1_C4_S1_Numpy_PracticeBrief.csv', delimiter=',', skip_header=1)
print("Employees :\n", emp_details)
avrg_age= np.mean(emp_details)
print("Average age: ",avrg_age)

Employees :
 [[ 1. 22.]
 [ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 8. 23.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [13. 22.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [18. 22.]
 [19. 25.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [23. 24.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [34. 24.]
 [35. 24.]
 [36. 23.]
 [37. 28.]
 [38. 28.]
 [39. 22.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [47. 22.]
 [48. 23.]
 [49. 32.]
 [50. 34.]]
Average age:  26.88


In [123]:
# TASK- 11

from numpy import genfromtxt

ind=np.where(emp_details[:,1]>25)
print("Employees aged greater than 25:\n",emp_details[ind])



Employees aged greater than 25:
 [[ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [37. 28.]
 [38. 28.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [49. 32.]
 [50. 34.]]


In [7]:
# TASK- 12

import numpy as np
from numpy import genfromtxt
emp_details= genfromtxt('DS1_C4_S1_Numpy_PracticeBrief.csv', delimiter=',', skip_header=1)
#res=np.where(np.logical_and(Age>=30, Age<=35))
res=np.where(np.logical_and(emp_details[:,1]>30,emp_details[:,1]<35))
print(emp_details[res])



[[ 3. 31.]
 [10. 32.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [43. 33.]
 [44. 31.]
 [49. 32.]
 [50. 34.]]
